import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bayesian Mass Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://bmex.dev">BMEX!</a>
        </h1>

        <p className={styles.description}>
          Explore masses in the Bayesian way!  
        </p>

        <div className={styles.grid}>
          <Link href="/plots" className={styles.card}>
	  <a>
            <h2>Plots &rarr;</h2>
            <p>Placeholder plot page! We can decide how we want to interact soon.</p>
          </a>
	  </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/kylegodbey/bmex-static">&copy; 2021 BMEX Team</a>
      </footer>
    </div>
  )
}
