import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Plots() {
  return (
	<iframe src="https://bmex.azurewebsites.net" width="100%" title="BMEX App"></iframe>
  )
}
#export default function Plots() {
# return (
#   <div className={styles.container}>
#     <Head>
#       <title>Bayesian Mass Explorer</title>
#       <meta name="description" content="Generated by create next app" />
#       <link rel="icon" href="/favicon.ico" />
#     </Head>
#
#     <main className={styles.main}>
#       <h1 className={styles.title}>
#         Welcome to <a href="https://bmex.dev">BMEX!</a>
#       </h1>
#
#       <p className={styles.description}>
#         Explore masses in the Bayesian way!  
#       </p>
#
#       <iframe src="https://bmex.azurewebsites.net" width="100%" title="BMEX App"></iframe>
#     </main>
#
#     <footer className={styles.footer}>
#     </footer>
#   </div>
# )
#}
